/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    categories: Category;
    media: Media;
    posts: Post;
    pages: Page;
    users: User;
    alerts: Alert;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    mainMenu: MainMenu;
  };
}
export interface Category {
  id: string;
  name?: string;
  archived?: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes?: {
    thumbnail?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    portrait?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    hero?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
}
export interface Post {
  id: string;
  title?: string;
  category?: string[] | Category[];
  layout?: (
    | {
        columns?: {
          width: 'oneThird' | 'half' | 'twoThirds' | 'full';
          alignment: 'left' | 'center' | 'right';
          richText?: {
            [k: string]: unknown;
          }[];
          links?: {
            link: {
              type?: 'reference' | 'custom';
              label: string;
              reference:
                | {
                    relationTo: 'pages';
                    value: string | Page;
                  }
                | {
                    relationTo: 'posts';
                    value: string | Post;
                  };
              url: string;
              newTab?: boolean;
            };
            id?: string;
          }[];
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'content';
      }
    | {
        media: string | Media;
        useVimeo?: boolean;
        vimeoID: string;
        aspectRatio?: '56.25' | '75';
        size?: 'normal' | 'wide' | 'fullscreen';
        caption?: {
          [k: string]: unknown;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'media';
      }
    | {
        alignment: 'contentOnLeft' | 'contentOnRight';
        richText?: {
          [k: string]: unknown;
        }[];
        media: string | Media;
        embeddedVideo: {
          embed?: boolean;
          poster?: string | Media;
          platform?: 'youtube' | 'vimeo';
          videoID: string;
          aspectRatio?: '56.25' | '75';
        };
        links?: {
          link: {
            appearance?: 'text' | 'primaryButton' | 'secondaryButton';
            type?: 'reference' | 'custom';
            label: string;
            reference:
              | {
                  relationTo: 'pages';
                  value: string | Page;
                }
              | {
                  relationTo: 'posts';
                  value: string | Post;
                };
            url: string;
            newTab?: boolean;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'mediaContent';
      }
    | {
        introContent?: {
          [k: string]: unknown;
        }[];
        slides?: {
          media: string | Media;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'mediaSlider';
      }
  )[];
  author?: string | User;
  publishDate?: string;
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface Page {
  id: string;
  title: string;
  hero?: {
    type?:
      | 'basic'
      | 'content'
      | 'contentMedia'
      | 'contentSidebar'
      | 'quickNav'
      | 'fullscreenBackground'
      | 'fullscreenSlider';
    basic?: {
      richText?: {
        [k: string]: unknown;
      }[];
      links?: {
        link: {
          appearance?: 'text' | 'primaryButton' | 'secondaryButton';
          type?: 'reference' | 'custom';
          label: string;
          reference:
            | {
                relationTo: 'pages';
                value: string | Page;
              }
            | {
                relationTo: 'posts';
                value: string | Post;
              };
          url: string;
          newTab?: boolean;
        };
        id?: string;
      }[];
    };
    content?: {
      richText?: {
        [k: string]: unknown;
      }[];
      links?: {
        link: {
          appearance?: 'text' | 'primaryButton' | 'secondaryButton';
          type?: 'reference' | 'custom';
          label: string;
          reference:
            | {
                relationTo: 'pages';
                value: string | Page;
              }
            | {
                relationTo: 'posts';
                value: string | Post;
              };
          url: string;
          newTab?: boolean;
        };
        id?: string;
      }[];
    };
    contentMedia?: {
      richText?: {
        [k: string]: unknown;
      }[];
      links?: {
        link: {
          appearance?: 'text' | 'primaryButton' | 'secondaryButton';
          type?: 'reference' | 'custom';
          label: string;
          reference:
            | {
                relationTo: 'pages';
                value: string | Page;
              }
            | {
                relationTo: 'posts';
                value: string | Post;
              };
          url: string;
          newTab?: boolean;
        };
        id?: string;
      }[];
      media?: string | Media;
      embeddedVideo: {
        embed?: boolean;
        poster?: string | Media;
        platform?: 'youtube' | 'vimeo';
        videoID: string;
        aspectRatio?: '56.25' | '75';
      };
    };
    contentSidebar?: {
      mainContent?: {
        [k: string]: unknown;
      }[];
      links?: {
        link: {
          appearance?: 'text' | 'primaryButton' | 'secondaryButton';
          type?: 'reference' | 'custom';
          label: string;
          reference:
            | {
                relationTo: 'pages';
                value: string | Page;
              }
            | {
                relationTo: 'posts';
                value: string | Post;
              };
          url: string;
          newTab?: boolean;
        };
        id?: string;
      }[];
      sidebarContent?: {
        [k: string]: unknown;
      }[];
    };
    fullscreenBackground?: {
      backgroundMedia: string | Media;
      richText?: {
        [k: string]: unknown;
      }[];
      links?: {
        link: {
          appearance?: 'text' | 'primaryButton' | 'secondaryButton';
          type?: 'reference' | 'custom';
          label: string;
          reference:
            | {
                relationTo: 'pages';
                value: string | Page;
              }
            | {
                relationTo: 'posts';
                value: string | Post;
              };
          url: string;
          newTab?: boolean;
        };
        id?: string;
      }[];
    };
    quickNav?: {
      backgroundMedia: string | Media;
      richText?: {
        [k: string]: unknown;
      }[];
      links?: {
        link: {
          appearance?: 'text' | 'primaryButton' | 'secondaryButton';
          type?: 'reference' | 'custom';
          label: string;
          reference:
            | {
                relationTo: 'pages';
                value: string | Page;
              }
            | {
                relationTo: 'posts';
                value: string | Post;
              };
          url: string;
          newTab?: boolean;
        };
        id?: string;
      }[];
      columns?: {
        heading: string;
        description: string;
        link: {
          type?: 'reference' | 'custom';
          reference:
            | {
                relationTo: 'pages';
                value: string | Page;
              }
            | {
                relationTo: 'posts';
                value: string | Post;
              };
          url: string;
          newTab?: boolean;
        };
        id?: string;
      }[];
    };
    fullscreenSlider?: {
      useStaticContent?: boolean;
      richText?: {
        [k: string]: unknown;
      }[];
      links?: {
        link: {
          appearance?: 'text' | 'primaryButton' | 'secondaryButton';
          type?: 'reference' | 'custom';
          label: string;
          reference:
            | {
                relationTo: 'pages';
                value: string | Page;
              }
            | {
                relationTo: 'posts';
                value: string | Post;
              };
          url: string;
          newTab?: boolean;
        };
        id?: string;
      }[];
      slides?: {
        backgroundMedia: string | Media;
        richText?: {
          [k: string]: unknown;
        }[];
        links?: {
          link: {
            appearance?: 'text' | 'primaryButton' | 'secondaryButton';
            type?: 'reference' | 'custom';
            label: string;
            reference:
              | {
                  relationTo: 'pages';
                  value: string | Page;
                }
              | {
                  relationTo: 'posts';
                  value: string | Post;
                };
            url: string;
            newTab?: boolean;
          };
          id?: string;
        }[];
        id?: string;
      }[];
    };
  };
  layout?: (
    | {
        appearance?: 'default' | 'condensed';
        sections?: {
          label: string;
          openOnInit?: boolean;
          columns?: {
            width: 'oneThird' | 'half' | 'twoThirds' | 'full';
            alignment: 'left' | 'center' | 'right';
            richText?: {
              [k: string]: unknown;
            }[];
            links?: {
              link: {
                type?: 'reference' | 'custom';
                label: string;
                reference:
                  | {
                      relationTo: 'pages';
                      value: string | Page;
                    }
                  | {
                      relationTo: 'posts';
                      value: string | Post;
                    };
                url: string;
                newTab?: boolean;
              };
              id?: string;
            }[];
            id?: string;
          }[];
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'accordion';
      }
    | {
        columns?: {
          width: 'oneThird' | 'half' | 'twoThirds' | 'full';
          alignment: 'left' | 'center' | 'right';
          richText?: {
            [k: string]: unknown;
          }[];
          links?: {
            link: {
              type?: 'reference' | 'custom';
              label: string;
              reference:
                | {
                    relationTo: 'pages';
                    value: string | Page;
                  }
                | {
                    relationTo: 'posts';
                    value: string | Post;
                  };
              url: string;
              newTab?: boolean;
            };
            id?: string;
          }[];
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'content';
      }
    | {
        richText?: {
          [k: string]: unknown;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'embeddedForm';
      }
    | {
        media: string | Media;
        useVimeo?: boolean;
        vimeoID: string;
        aspectRatio?: '56.25' | '75';
        size?: 'normal' | 'wide' | 'fullscreen';
        caption?: {
          [k: string]: unknown;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'media';
      }
    | {
        alignment: 'contentOnLeft' | 'contentOnRight';
        richText?: {
          [k: string]: unknown;
        }[];
        media: string | Media;
        embeddedVideo: {
          embed?: boolean;
          poster?: string | Media;
          platform?: 'youtube' | 'vimeo';
          videoID: string;
          aspectRatio?: '56.25' | '75';
        };
        links?: {
          link: {
            appearance?: 'text' | 'primaryButton' | 'secondaryButton';
            type?: 'reference' | 'custom';
            label: string;
            reference:
              | {
                  relationTo: 'pages';
                  value: string | Page;
                }
              | {
                  relationTo: 'posts';
                  value: string | Post;
                };
            url: string;
            newTab?: boolean;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'mediaContent';
      }
    | {
        introContent?: {
          [k: string]: unknown;
        }[];
        slides?: {
          media: string | Media;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'mediaSlider';
      }
  )[];
  fullTitle?: string;
  slug?: string;
  author?: string | User;
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface User {
  id: string;
  name?: string;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean;
  apiKey?: string;
  apiKeyIndex?: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Alert {
  id: string;
  name?: string;
  placement: 'global' | 'documents';
  documents:
    | {
        relationTo: 'pages';
        value: string;
      }[]
    | {
        relationTo: 'pages';
        value: Page;
      }[];
  backgroundColor?: 'matchTheme' | 'green' | 'blue' | 'red' | 'purple';
  content: {
    [k: string]: unknown;
  }[];
  links?: {
    link: {
      appearance?: 'text' | 'primaryButton' | 'secondaryButton';
      type?: 'reference' | 'custom';
      label: string;
      reference:
        | {
            relationTo: 'pages';
            value: string | Page;
          }
        | {
            relationTo: 'posts';
            value: string | Post;
          };
      url: string;
      newTab?: boolean;
    };
    id?: string;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string;
  batch?: number;
  schema?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface MainMenu {
  id: string;
  items?: {
    type?: 'link' | 'subMenu';
    label: string;
    subMenu?: {
      blocks?: (
        | {
            title: string;
            id?: string;
            blockName?: string;
            blockType: 'menuTitle';
          }
        | {
            appearance?: 'primary' | 'secondary' | 'arrow';
            link: {
              type?: 'reference' | 'custom';
              label: string;
              reference:
                | {
                    relationTo: 'pages';
                    value: string | Page;
                  }
                | {
                    relationTo: 'posts';
                    value: string | Post;
                  };
              url: string;
              newTab?: boolean;
            };
            id?: string;
            blockName?: string;
            blockType: 'menuLink';
          }
        | {
            content: string;
            id?: string;
            blockName?: string;
            blockType: 'menuDescription';
          }
        | {
            menuFeatureMedia: string | Media;
            headline: string;
            link: {
              type?: 'reference' | 'custom';
              reference:
                | {
                    relationTo: 'pages';
                    value: string | Page;
                  }
                | {
                    relationTo: 'posts';
                    value: string | Post;
                  };
              url: string;
              newTab?: boolean;
            };
            id?: string;
            blockName?: string;
            blockType: 'menuFeature';
          }
      )[];
    };
    link?: {
      type?: 'reference' | 'custom';
      reference:
        | {
            relationTo: 'pages';
            value: string | Page;
          }
        | {
            relationTo: 'posts';
            value: string | Post;
          };
      url: string;
      newTab?: boolean;
    };
    id?: string;
  }[];
  updatedAt?: string;
  createdAt?: string;
}
